<?php
/**
 * Created by PhpStorm.
 * User: Dell
 * Date: 3/26/2018
 * Time: 11:37 AM
 */

class FosUserType extends \Symfony\Component\Form\AbstractType
{
    public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options)
    {
//        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('username','text', array(
                'required'=>true,
                'attr' => array(
                    "class" => "from-control",
                )
            ))
        ;
    }
}